### ISSUE TITLE
Possible bug or unnecessary comparison

### ISSUE THREAD

**Issue by bringhurst** [chaos/slurm#22]
In src/slurmdbd/proc_req.c at roughly line 1252:

``` C
if (get_jobs_msg->gid >=0) {
    char *temp = xstrdup_printf("%u", get_jobs_msg->gid);
    job_cond.groupid_list = list_create(slurm_destroy_char);
    list_append(job_cond.groupid_list, temp);
}
```

get_jobs_msg->gid is unsigned, so (get_jobs_msg->gid >=0) will always return true.

In addition, in src/slurmctld/proc_req.c at around line 3667:

``` C
if (launch_msg_ptr->ntasks < 0)
    launch_msg_ptr->ntasks = job_ptr->cpu_cnt;
```

launch_msg_ptr->ntasks is unsigned, so (launch_msg_ptr->ntasks < 0) will always return false.

**Comment by jette** [comment]
this is vestigial (unused) code and I will remove shortly

**Comment by jette** [comment]
Code removed in slurm v2.2.0-pre6, which will be released soon
