### ISSUE TITLE
squeue -u: num_nodes for pending jobs

### ISSUE THREAD

**Issue by ax3l** [chaos/slurm#45]
`squeue -u <username` shows the number of requested CPUs (`%.7C`) instead of the number of _NODES_ (`%.7D`) for **pending jobs**.

The output is correct for **running jobs**.
For _queue lists_, e.g. `squeue -p <queue>`, the output is correct for all types (pending, running, ...).

I guess the problem resides somewhere around the [6 lines](https://github.com/chaos/slurm/blob/master/src/squeue/print.c#L757-L762) here?

**Comment by grondo** [comment]
Good catch. However, the master branch in chaos/slurm is currently unmaintained. Are you running
a version from the maintained branch (slurm-2.3.3.chaos)?

If not perhaps you want to open a bug against SchedMD/slurm.

(btw, it does seem like you found the right lines to patch. Nice work)

**Comment by ax3l** [comment]
Hi grondo, thanks for the fast response :)
I realized its a `slurm 2.6.0-Bull.2.8` running on our system, so I will refer to [schedMD/slurm](https://github.com/schedMD/slurm) !

Thanks!
