### ISSUE TITLE
PBS_NODEFILE

### ISSUE THREAD

**Issue by ghost** [chaos/slurm#48]
Hello,

I wonder why the PERL script in contribs, generate_pbs_nodefile.pl, contributed by @dannyauble & @ryanbcox in the ShedMD's fork of this project (https://github.com/SchedMD/slurm/blob/master/contribs/torque/generate_pbs_nodefile.pl) is not present in the original repo (here) ; This script is useful to generate a PBS-style nodefile and soften the transition from PBS to SLURM. As far as I know, this script in the ShedMD's fork needs some updating (the statement use lib "${FindBin::Bin}/../lib/perl"; for instance, seems outdated). I would need this script to generate a PBS_NODEFILE in order to migrate some code written for PBS to SLURM without much modifications.

Best,

**Comment by dannyauble** [comment]
The original chaos repo is quite or of date.  I expect a large amount of code doesn't exist there.  All development is done in the SchedMD repo.

**Comment by ghost** [comment]
OK :-) ; I had noticed that the trees and tags where different but I hadn't noticed the date. Thanks for the reply. I'll open an issue there.
